name:          Guía de Código de @mdo
description:   Estándares para el desarrollo de HTML y CSS flexibles, duraderos y mantenibles.
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
